wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.6
    framework: huggingface
    huggingface_version: 4.9.2
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.2
    start_time: 1636966240
    t:
      1:
      - 1
      - 5
      - 11
      2:
      - 1
      - 5
      - 11
      4: 3.8.2
      5: 0.12.6
      6: 4.9.2
      8:
      - 1
      - 3
      - 5
